# path
database : "/home/jcdenton/projects/mirgenedb_database/"
prifile : "merged_all-pri-30-30.fas"
ref : "mirgenedb_mature_star_genome/"
extend_ref : "mirgenedb_merged_extended_genome/"
bowtie_ref : "mirgenedb_merged_extended_reference/"
seq_data : /home/jcdenton/projects/smallRNAseq/
sam : "mirgenedb_merged_extended_sam/"
filtered_no_pos_2_18_mis : "mirgenedb_merged_extended_sam_filtered_no_pos2_18_mismatch/"
filtered_no_outside_pos_2_18_mis : "mirgenedb_merged_extended_sam_filtered_no_outside_pos2_18_mismatch/"
species_dict : "species_dict.txt"
editing_events : 'counted_mismatches/'
editing_events_aggregated : 'counted_mismatches_aggregated/'
counted_mismatches_collapsed_species : 'counted_mismatches_collapsed_species/'
counted_mismatches_collapsed_tissue : 'counted_mismatches_collapsed_tissue/'